spring:
  application:
    name: emotion-storage
  profiles:
    active: local
  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: "scheduled-task-"

rest-template:
  connect-timeout: 5000
  read-timeout: 120000

monitoring:
  discord:
    enabled: true
    error-webhook-url: ${DISCORD_ERROR_WEBHOOK_URL:}
